version: '3.1'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwerty123ASDFGJKLJKIE845yrtu
      POSTGRES_DB: postgres
    networks:
      - app-network

  django:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - redis


networks:
  app-network:
    driver: bridge
